# Generated by Django 5.1.4 on 2025-05-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='loyalty_points',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='preferred_category',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='preferred_skin_type',
        ),
    ]
