# Generated by Django 5.1.4 on 2025-06-02 19:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_productrecommendation_alter_product_options_and_more'),
        ('users', '0012_alter_customer_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='customer_profiles/')),
                ('skin_type', models.CharField(blank=True, choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('normal', 'Normal'), ('sensitive', 'Sensitive'), ('not_sure', 'Not Sure')], max_length=20, null=True)),
                ('undertone', models.CharField(blank=True, choices=[('cool', 'Cool'), ('warm', 'Warm'), ('neutral', 'Neutral'), ('olive', 'Olive'), ('not_sure', 'Not Sure')], max_length=10, null=True)),
                ('surface_tone', models.CharField(blank=True, choices=[('very_fair', 'Very Fair'), ('fair', 'Fair'), ('light', 'Light'), ('medium', 'Medium'), ('tan', 'Tan'), ('dark', 'Dark'), ('very_dark', 'Very Dark')], max_length=20, null=True)),
                ('primary_skin_concerns', models.CharField(blank=True, help_text='Comma-separated list of skin concerns', max_length=255, null=True)),
                ('skin_sensitivity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('known_allergies', models.TextField(blank=True, null=True)),
                ('preferred_finish', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_coverage', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_texture', models.CharField(blank=True, max_length=20, null=True)),
                ('ethical_preferences', models.JSONField(blank=True, default=list, help_text="List of ethical preferences (e.g., ['vegan', 'cruelty_free'])")),
                ('last_skin_assessment', models.DateTimeField(blank=True, null=True)),
                ('skin_assessment_version', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
            },
        ),
        migrations.CreateModel(
            name='SkinAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('hydration_level', models.IntegerField(help_text='1 (Very Dry) to 5 (Very Hydrated)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('oiliness_level', models.IntegerField(help_text='1 (Not Oily) to 5 (Very Oily)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sensitivity_level', models.IntegerField(help_text='1 (Not Sensitive) to 5 (Very Sensitive)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('acne_proneness', models.IntegerField(help_text='1 (Not Prone) to 5 (Very Prone)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('aging_concerns', models.IntegerField(help_text='1 (No Concerns) to 5 (Severe Concerns)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('current_routine', models.TextField(blank=True, null=True)),
                ('current_concerns', models.TextField(blank=True, null=True)),
                ('goals', models.TextField(blank=True, null=True)),
                ('recommendation_notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_assessments', to='users.customerprofile')),
            ],
            options={
                'verbose_name': 'Skin Assessment',
                'verbose_name_plural': 'Skin Assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='SomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
