# Generated by Django 5.1.4 on 2025-06-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customerprofile_skinassessment_somemodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='primary_skin_concerns',
            new_name='concerns',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='skin_sensitivity',
            new_name='sensitivity_level',
        ),
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
