# Generated by Django 5.1.4 on 2025-06-03 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_primary_skin_concerns_customerprofile_concerns_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkinAssessment',
        ),
    ]
