# Generated by Django 5.1.4 on 2025-06-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customerprofile_first_name_customerprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
