# Generated by Django 5.1.4 on 2025-06-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customerprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='customer_photo/'),
        ),
    ]
