# Generated by Django 5.1.4 on 2025-01-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('min_stock', models.PositiveIntegerField(default=0)),
                ('max_stock', models.PositiveIntegerField(default=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('variation_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('skin_type', models.CharField(blank=True, choices=[('Oily', 'Oily'), ('Dry', 'Dry'), ('Combination', 'Combination'), ('Normal', 'Normal')], max_length=20, null=True)),
                ('skin_condition', models.CharField(blank=True, choices=[('Acne-Prone', 'Acne-Prone'), ('Sensitive', 'Sensitive'), ('Dehydrated', 'Dehydrated')], max_length=20, null=True)),
                ('skin_tone', models.CharField(blank=True, choices=[('Cool Undertone', 'Cool Undertone'), ('Warm Undertone', 'Warm Undertone'), ('Neutral Undertone', 'Neutral Undertone')], max_length=20, null=True)),
                ('surface_tones', models.CharField(blank=True, choices=[('Sangat Cerah', 'Sangat Cerah'), ('Cerah', 'Cerah'), ('Terang', 'Terang'), ('Sederhana', 'Sederhana'), ('Sawo Matang', 'Sawo Matang'), ('Gelap', 'Gelap'), ('Sangat Gelap', 'Sangat Gelap')], max_length=20, null=True)),
                ('skin_texture', models.CharField(blank=True, choices=[('Licin', 'Licin'), ('Kasar', 'Kasar'), ('Pori Besar', 'Pori Besar'), ('Berparut', 'Berparut'), ('Berkedut', 'Berkedut')], max_length=20, null=True)),
                ('sensitivity_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
