# Generated by Django 5.1.4 on 2025-05-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_customer_order_status_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
