# Generated by Django 5.1.4 on 2025-05-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_productimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
