# Generated by Django 5.1.4 on 2025-05-23 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_productimage_image_alter_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='skin_tone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='surface_tones',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='skin_tone',
            field=models.CharField(blank=True, choices=[('Cool Undertone', 'Cool Undertone'), ('Warm Undertone', 'Warm Undertone'), ('Neutral Undertone', 'Neutral Undertone')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='surface_tones',
            field=models.CharField(blank=True, choices=[('Sangat Cerah', 'Sangat Cerah'), ('Cerah', 'Cerah'), ('Terang', 'Terang'), ('Sederhana', 'Sederhana'), ('Sawo Matang', 'Sawo Matang'), ('Gelap', 'Gelap'), ('Sangat Gelap', 'Sangat Gelap')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='store.product'),
        ),
    ]
