# Generated by Django 5.1.4 on 2025-05-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_product_skin_tone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variation_code',
        ),
    ]
