# Generated by Django 5.1.4 on 2025-05-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.CharField(blank=True, choices=[('matte', 'Matte'), ('dewy', 'Dewy'), ('satin', 'Satin'), ('glitter', 'Glitter')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_cruelty_free',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_vegan',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='long_last',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tahan Lama?'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='Size', help_text='e.g., 30ml, 50g', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='suitable_for',
            field=models.CharField(choices=[('all', 'All Skin Types'), ('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('normal', 'Normal'), ('sensitive', 'Sensitive')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='texture',
            field=models.CharField(blank=True, choices=[('liquid', 'Liquid'), ('cream', 'Cream'), ('powder', 'Powder'), ('stick', 'Stick'), ('gel', 'Gel')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='waterproof',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sensitivity_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('all', 'All Skin Types'), ('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('normal', 'Normal'), ('sensitive', 'Sensitive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
