# Generated by Django 5.1.4 on 2025-05-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_product_coverage_product_spf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='spf',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
