# Generated by Django 5.1.4 on 2025-05-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_product_spf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coverage',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('medium', 'Medium'), ('full', 'Full'), ('buildable', 'Buildable')], max_length=20, null=True),
        ),
    ]
