# Generated by Django 5.1.4 on 2025-06-02 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_order_shipping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text="How well this product matches the customer's profile (0-1)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('reason', models.CharField(blank=True, help_text='Why this product was recommended', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-match_score'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-popularity_score', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Detailed product benefits and features', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hypoallergenic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='popularity_score',
            field=models.FloatField(default=0.0, help_text='Product popularity based on views/purchases'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for search', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='hex_color',
            field=models.CharField(blank=True, help_text='Hex color code for display', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_condition',
            field=models.CharField(blank=True, help_text='Comma-separated list of conditions this product addresses', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_texture',
            field=models.CharField(blank=True, choices=[('smooth', 'Smooth'), ('rough', 'Rough'), ('large_pores', 'Large Pores'), ('scarred', 'Scarred'), ('wrinkled', 'Wrinkled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='skin_tone',
            field=models.CharField(blank=True, choices=[('cool', 'Cool Undertone'), ('warm', 'Warm Undertone'), ('neutral', 'Neutral Undertone'), ('olive', 'Olive Undertone')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='surface_tones',
            field=models.CharField(blank=True, choices=[('very_fair', 'Very Fair'), ('fair', 'Fair'), ('light', 'Light'), ('medium', 'Medium'), ('tan', 'Tan'), ('dark', 'Dark'), ('very_dark', 'Very Dark')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'variation_code')},
        ),
    ]
