# Generated by Django 5.1.4 on 2025-06-03 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_remove_shippingaddress_user_customeraddress'),
        ('users', '0015_delete_skinassessment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrecommendation',
            options={'ordering': ['-match_score'], 'verbose_name': 'Product Recommendation', 'verbose_name_plural': 'Product Recommendations'},
        ),
        migrations.AlterModelOptions(
            name='productvariation',
            options={'verbose_name': 'Product Variation', 'verbose_name_plural': 'Product Variations'},
        ),
        migrations.AlterField(
            model_name='product',
            name='finish',
            field=models.CharField(blank=True, choices=[('matte', 'Matte'), ('dewy', 'Dewy'), ('satin', 'Satin'), ('glitter', 'Glitter')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='popularity_score',
            field=models.FloatField(default=0.0, help_text='Product popularity normalized over all in-stock items'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended_for',
            field=models.ManyToManyField(related_name='recommended_products', through='store.ProductRecommendation', to='users.customerprofile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text="Comma-separated tags for search (e.g. 'hydrating,non_comedogenic')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='match_score',
            field=models.FloatField(help_text="How well this product matches the customer's profile (0–1)", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='productrecommendation',
            name='reason',
            field=models.CharField(blank=True, help_text="Short explanation (e.g., 'Content:0.8 | Rule:0.5 | Shade:Yes')", max_length=255),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='hex_color',
            field=models.CharField(blank=True, help_text="Hex color code for display (e.g. '#F2C4A1')", max_length=7, null=True),
        ),
    ]
