# Generated by Django 5.1.4 on 2025-06-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_product_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='long_last',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Long Lasting?'),
        ),
    ]
