# Generated by Django 5.1.4 on 2025-06-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(choices=[('all', 'All Skin Types'), ('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('normal', 'Normal'), ('sensitive', 'Sensitive')], default='normal', max_length=20)),
                ('concerns', models.CharField(blank=True, help_text='Comma-separated (e.g., Acne-Prone, Sensitive)', max_length=200)),
                ('undertone', models.CharField(blank=True, choices=[('cool', 'Cool Undertone'), ('warm', 'Warm Undertone'), ('neutral', 'Neutral Undertone'), ('olive', 'Olive Undertone')], max_length=20)),
                ('sensitivity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('texture_preference', models.CharField(blank=True, choices=[('liquid', 'Liquid'), ('cream', 'Cream'), ('powder', 'Powder'), ('stick', 'Stick'), ('gel', 'Gel')], max_length=20)),
                ('finish_preference', models.CharField(blank=True, choices=[('matte', 'Matte'), ('dewy', 'Dewy'), ('satin', 'Satin'), ('glitter', 'Glitter')], max_length=20)),
            ],
        ),
    ]
