# Generated by Django 5.1.4 on 2025-06-02 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendation', '0001_initial'),
        ('users', '0013_customerprofile_skinassessment_somemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinprofile',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skin_profile', to='users.customerprofile'),
        ),
    ]
