# Generated by Django 5.1.4 on 2025-06-03 10:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_initial'),
        ('users', '0015_delete_skinassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('hydration_level', models.IntegerField(help_text='1=very dry, 5=very hydrated', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('oiliness_level', models.IntegerField(help_text='1=very non-oily, 5=extremely oily', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sensitivity_level', models.IntegerField(help_text='1=not sensitive, 5=very sensitive', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('acne_proneness', models.IntegerField(help_text='1=never acne, 5=always acne', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('aging_concerns', models.IntegerField(help_text='1=no aging issues, 5=major wrinkles/aging', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('skin_type', models.CharField(choices=[('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination'), ('normal', 'Normal'), ('sensitive', 'Sensitive')], help_text='Pick the one that best describes your overall skin type', max_length=20)),
                ('undertone', models.CharField(choices=[('cool', 'Cool'), ('warm', 'Warm'), ('neutral', 'Neutral'), ('olive', 'Olive')], help_text='Your natural undertone', max_length=20)),
                ('concerns', models.CharField(blank=True, help_text='Comma-separated list of concerns (e.g. acne, redness)', max_length=255)),
                ('finish_preference', models.CharField(blank=True, choices=[('matte', 'Matte'), ('dewy', 'Dewy'), ('satin', 'Satin'), ('glitter', 'Glitter')], help_text='If you prefer matte/ dewy / satin etc.', max_length=20, null=True)),
                ('texture_preference', models.CharField(blank=True, choices=[('liquid', 'Liquid'), ('cream', 'Cream'), ('powder', 'Powder'), ('stick', 'Stick'), ('gel', 'Gel')], help_text='If you prefer liquid/cream/ powder etc.', max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_assessments', to='users.customerprofile')),
            ],
            options={
                'verbose_name': 'Skin Assessment',
                'verbose_name_plural': 'Skin Assessments',
                'ordering': ['-assessment_date'],
            },
        ),
    ]
