# Generated by Django 5.1.4 on 2025-06-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_skinassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinassessment',
            name='surface_tone',
            field=models.CharField(blank=True, choices=[('very_fair', 'Very Fair'), ('fair', 'Fair'), ('light', 'Light'), ('medium', 'Medium'), ('tan', 'Tan'), ('dark', 'Dark'), ('very_dark', 'Very Dark')], max_length=20, null=True),
        ),
    ]
