# Generated by Django 5.1.4 on 2025-06-19 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_skinassessment_surface_tone'),
        ('store', '0047_alter_product_long_last'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('purchase', 'Purchase')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'product'], name='recommendat_user_id_372a5c_idx'), models.Index(fields=['event_type'], name='recommendat_event_t_38a5b3_idx'), models.Index(fields=['timestamp'], name='recommendat_timesta_0a9fad_idx')],
            },
        ),
    ]
